#!/bin/sh

uci -q batch <<-EOF
	# System
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	set system.@system[0].hostname='link-to-the-future'
	set system.ntp.use_dhcp='0'
	set system.@system[0].urandom_seed='1'
	commit system

	# Network
	set network.globals.ula_prefix='fd0f:7a7c:a8c9::/48'
	set network.globals.dhcp_default_duid='0004b8942260f95a40bba37111df97df7728'
	del network.wan6
	set network.wan.peerdns='0'
	del network.wan.dns
	add_list network.wan.dns='127.0.0.1'
	set network.wan.proto='pppoe'
	set network.wan.ipv6='auto'
	set network.@device[0].arp_accept='1'
	set network.@device[0].packet_steering=0
	set network.@device[0].flow_offloading=0
	set network.@device[0].flow_offloading_hw=0
	commit network

	# Firewall defaults
	set firewall.@defaults[0].tcp_ecn='1'
	set firewall.@defaults[0].flow_offloading='0'
	set firewall.@defaults[0].flow_offloading_hw='0'
	set firewall.@zone[1].network='wan'

	# DHCP / IPv6 RA
	set dhcp.lan.ra_preference='high'
	del dhcp.lan.ra_flags
	add_list dhcp.lan.ra_flags='other-config'
	set dhcp.lan.ra_default='1'
	del dhcp.lan.dns
	add_list dhcp.lan.dns='fd0f:7a7c:a8c9::1'
	set dhcp.lan.leasetime='21d'
	set dhcp.lan.ra_maxinterval='600'
	set dhcp.lan.ra_mininterval='200'
	set dhcp.lan.ra_lifetime='9000'
	set dhcp.odhcpd.maindhcp='1'
	commit dhcp

	# WiFi
	set wireless.radio0.country='PA'
	set wireless.radio1.country='PA'
	set wireless.@wifi-iface[0].disabled=0
	set wireless.@wifi-iface[1].disabled=0
	set wireless.radio1.htmode='HE20'
	set wireless.radio0.htmode='HE160'
	set wireless.default_radio0.ssid='Link to the FUTURE'
	set wireless.default_radio1.ssid='Xiaomi_391F'
	set wireless.default_radio1.encryption='psk2+ccmp'
	set wireless.default_radio1.key='1qaz@WSX'
	set wireless.default_radio0.encryption='psk2+ccmp'
	set wireless.default_radio0.key='1qaz@WSX'
	set wireless.default_radio0.dtim_period='5'
	set wireless.radio1.txpower='15'
	set wireless.radio0.txpower='20'
	set wireless.radio0.channel='36'
	set wireless.radio0.cell_density='0'
	set wireless.radio1.cell_density='0'
	set wireless.radio1.channel='6'
	set wireless.default_radio0.beacon_int='97'
	set wireless.default_radio0.multicast_to_unicast_all='1'
	set wireless.default_radio1.max_inactivity='86400'
	commit wireless

	# IoT interface
	set network.iot=interface
	set network.iot.proto='static'
	del network.iot.ipaddr
	add_list network.iot.ipaddr='192.168.3.1/24'
	commit network

	# IoT DHCP
	set dhcp.iot=dhcp
	set dhcp.iot.interface='iot'
	set dhcp.iot.start='100'
	set dhcp.iot.limit='150'
	set dhcp.iot.leasetime='infinite'
	set dhcp.iot.dhcpv4='server'
	set dhcp.iot.domain='iot'
	commit dhcp

	# IoT firewall zone (named section — runs once, no duplicates)
	set firewall.iot=zone
	set firewall.iot.name='iot'
	set firewall.iot.input='REJECT'
	set firewall.iot.output='ACCEPT'
	set firewall.iot.forward='REJECT'
	del firewall.iot.network
	add_list firewall.iot.network='iot'

	# IoT → WAN forwarding
	set firewall.iot_wan=forwarding
	set firewall.iot_wan.src='iot'
	set firewall.iot_wan.dest='wan'

	# IoT firewall rules (named sections)
	set firewall.rule_iot_dns=rule
	set firewall.rule_iot_dns.name='Iot DNS'
	set firewall.rule_iot_dns.src='iot'
	set firewall.rule_iot_dns.dest_port='53'
	set firewall.rule_iot_dns.target='ACCEPT'

	set firewall.rule_iot_dhcp=rule
	set firewall.rule_iot_dhcp.name='Iot DHCP'
	del firewall.rule_iot_dhcp.proto
	add_list firewall.rule_iot_dhcp.proto='udp'
	set firewall.rule_iot_dhcp.src='iot'
	set firewall.rule_iot_dhcp.dest_port='67-68'
	set firewall.rule_iot_dhcp.target='ACCEPT'

	set firewall.rule_iot_icmp=rule
	set firewall.rule_iot_icmp.name='Iot ICMP/IGMP'
	del firewall.rule_iot_icmp.proto
	add_list firewall.rule_iot_icmp.proto='icmp'
	add_list firewall.rule_iot_icmp.proto='igmp'
	set firewall.rule_iot_icmp.src='iot'
	set firewall.rule_iot_icmp.target='ACCEPT'

	set firewall.rule_iot_dhcp6=rule
	set firewall.rule_iot_dhcp6.name='Iot DHCPv6'
	del firewall.rule_iot_dhcp6.proto
	add_list firewall.rule_iot_dhcp6.proto='udp'
	set firewall.rule_iot_dhcp6.src='iot'
	set firewall.rule_iot_dhcp6.dest_port='546-547'
	set firewall.rule_iot_dhcp6.target='ACCEPT'

	set firewall.rule_iot_mdns=rule
	set firewall.rule_iot_mdns.name='Iot mDNS'
	del firewall.rule_iot_mdns.proto
	add_list firewall.rule_iot_mdns.proto='udp'
	set firewall.rule_iot_mdns.src='iot'
	set firewall.rule_iot_mdns.target='ACCEPT'
	set firewall.rule_iot_mdns.dest_port='5353'

	# Wireless network assignment (IoT)
	set wireless.default_radio1.network='iot'
	commit wireless
	commit firewall
EOF
