log:
    file: "/tmp/mosdns.log"
    level: error
    production: true            # 纯 json 输出。
api:
    http: ":65534"
plugins:
    - tag: cache
      type: cache
      args:
          size: 65536

    - args:
        concurrent: 3
        upstreams:
            - addr: https://1.12.12.12/dns-query
              max_conns: 5
              idle_timeout: 60
              # enable_http3: true
            - addr: https://223.5.5.5/dns-query
              # enable_http3: true
              max_conns: 5
              idle_timeout: 60
      tag: fast_forward
      type: forward
      
      
    - tag: seq
      type: sequence
      args:
          - exec: $cache
          - matches:
              - has_resp
            exec: accept
          - exec: $fast_forward
    - type: "udp_server"
      tag: "udp"
      args:
          entry: seq
          listen: ":5335"
    - tag: "tcp_server"
      type: "tcp_server"
      args:
          entry: seq  # 可执行插件的 tag。
          listen: ":5335" # 监听地址。


